### PR TITLE
Added kinesis hardware remapping

### PR DESCRIPTION
**Pull request by RoryNesbitt**
Prime showed me this repo a while back when I said I moved back to qwerty since I felt useless trying to type without my kinesis if I was used to dvorak. I love the idea but I don't want to have to install it on every machine I use when I can just spend some time setting up the keyboard to work that way itself.

So this is that, I don't have all your changes here and some parts are a little different since I have a us kinesis but a uk layout. So if there is interest here I'll edit it a bit more to have it better match your mappings

I also use they keypad layer as a keypad but without numlock so probably just ignore everything starting kp if you wanna have a look through

### CODE REVIEW

**Review by renerocksai — CHANGES_REQUESTED** [review]
Hi RoryNesbitt,

I feel honored that ThePrimeagen referred you here 😊!

This is *awesome*! I had wanted to do an advantage-only config (...) for quite some time now - but hadn't had a chance yet. Always too busy.

I really like your work and the effort you've put into this. However, I don't like to merge since I still use this repo as my canonical source of keyboard configuration. I have 2 advantage 2 keyboards, one in the office and one back home. So, whenever I change sth, I push it and pull it at the other site.

So what I suggest is: give your layout a cool name, like "Real Programmer's QWERTY UK" - and put it in `qwerty_uk.txt` or a separate folder if you want to keep the name `qwerty.txt`, which is totally understandable as this is what it's named on the Kinesis.

Then you can put a pointer to your file into the README - maybe describe the differences if you feel like it. That way, people who come here will have a choice.

What do you think?

Best,
Rene

**Comment by renerocksai** [comment]
BTW great idea to up the macro speed. I think, this will be the first change I'm going to steal from you.

**Comment by RoryNesbitt** [comment]
Thanks for the feedback. I stuck it in a kinesis folder to not interfere with your own config

That being said this still isn't ready for a merge, I mainly just wanted to gauge interest. Since you like the idea I'll finish matching your full setup and do some testing so the merged version can match the rest of the repo

**Comment by RoryNesbitt** [comment]
This seems to be fully working from my playing around. However there's a couple parts that might not be right with a us layout that seem right to me. I'll test this better before changing this from draft.  
I have moved your qwerty.txt file to the Kinesis sub directory and renamed mine qwerty-full.txt, and updated the readme to reflect this

Also, I have included the remapping I use which swaps <kbd>up</kbd> and <kbd>down</kbd> to make them match vim's <kbd>j</kbd> and <kbd>k</kbd>. I can remove that if you don't think it fits but I would suggest adding it to your main mappings as if you use vim the consistency is a great improvement

**Comment by renerocksai** [comment]
WOW! This looks really great! 

Your last commit message says you need someone to test the `#` to pound symbol remapping. I am not sure what you mean by that. 

I would like to merge your PR - you tell me when you're ready. 

Maybe I can help testing the US layout?

Regarding <kbd>up</kbd> and <kbd>down</kbd>: ... (checking out what you mean) ... OH. NOW I see what you mean. You reversed the order so it matches... This is BRILLIANT! I will add this to the main config! What a great idea! :+1:

**Comment by renerocksai** [comment]
BTW, as a side note, one reason I liked having a software-remapping alternative, is that with it, I can enjoy the remaps in the odd situation where I don't have access to my kinesis. This has not happened once since I got my first kinesis about a year ago. Once kinesis, there's simply no going back to a "normal" keyboard, if one can avoid it.

**Comment by RoryNesbitt** [comment]
There is absolutely no going back, I carry my kinesis to work and back. Very glad I can pass on the joy of reversing up and down.

I would consider this now ready to merge, the last commit relates to the UK layout as <kbd>~</kbd> is <kbd>Shift #</kbd>.  
<kbd>#</kbd> is where the US <kbd>\\</kbd> is, but my kinesis is the US firmware so I can't properly test UK.txt. I'm 90% sure it is good though.

**Comment by renerocksai** [comment]
Awesome! I will merge, then! And test the US layout - can't wait. Regarding UK: well, you did the best you could - and should there really be a problem with it: one can always raise an issue or send a PR. 

I just checked: I got myself a second kinesis just three weeks in: one for home, one for work. Taking the keyb to work and back is perfectly doable, it's not heavy. However, I started to fancy the silver one (my first and now office one is the black model, which I love, too) and not having to carry a keyboard was kind of how I justified getting it :smile:.

**Comment by renerocksai** [comment]
Thx again for your great work! I will test the mapping and tell you how it went!

**Comment by renerocksai** [comment]
**`YOU ARE A   G E N I U S   ! ! !`**

Dang! This is **awesome**! I can't believe it's all in the kinesis now! I just tested it. It's perfect! Even the high macro speed is there. I am **very** happy with it! 😁

👍 👍 👍 👍 👍

**Comment by RoryNesbitt** [comment]
Thank you very much man I appreciate that :D

**Comment by RoryNesbitt** [comment]
Couple small things about it:
As added to the readme, keys mapped via a macro will only enter once even when held
It relies on using <kbd>rshift + key</kbd> to macro things such as <kbd>*</kbd> (<kbd>rshift + 8</kbd>) as <kbd>lshift + 8</kbd> is now <kbd>8</kbd>. Therefore <kbd>rshift</kbd> has been mapped to <kbd>lshift</kbd>

**Pull request closed without merging**
